/// Compile-time configuration injected via `--dart-define-from-file=.env`.
///
/// Every value here originates from the `.env` file in the project root and
/// is baked into the binary at build time by the Dart compiler. They are not
/// readable at runtime from the filesystem; they exist only as Dart constants
/// after the build step resolves them.
///
/// Usage: always run the app with
///   `flutter run --dart-define-from-file=.env`
/// or the equivalent release flag:
///   `flutter build apk --dart-define-from-file=.env`
///
/// Firebase credentials are NOT sourced from here. Firebase is initialised
/// from the `lib/firebase_options.dart` file generated by `flutterfire
/// configure`, which writes platform-specific credentials into the native
/// Android and iOS project trees automatically.
///
/// Security boundary: both the Supabase publishable key and the EMQX
/// subscriber credentials are embedded in the compiled binary. This is
/// intentional and acceptable because:
/// - The publishable key carries SELECT-only permissions under RLS (Backend
///   Architecture Section 4.4). It cannot write to any table.
/// - The EMQX subscriber credential carries subscribe-only ACL permissions
///   (Backend Architecture Section 2.7). It cannot publish to any topic.
/// The Supabase secret key and the EMQX publisher credential are never
/// present in this file or anywhere in the Flutter project.
abstract final class AppConfig {
  // ---------------------------------------------------------------------------
  // Supabase
  // ---------------------------------------------------------------------------

  /// Full Supabase project URL, e.g. `https://<ref>.supabase.co`.
  /// Source: Supabase project Settings > API > Project URL.
  static const String supabaseUrl = String.fromEnvironment('SUPABASE_URL');

  /// Supabase publishable key (new-key-system equivalent of the legacy anon
  /// key). Carries SELECT-only permissions under the RLS policies defined in
  /// Backend Architecture Section 4.4.
  /// Source: Supabase project Settings > API > Project API keys.
  static const String supabasePublishableKey =
      String.fromEnvironment('SUPABASE_PUBLISHABLE_KEY');

  // ---------------------------------------------------------------------------
  // EMQX Cloud Serverless
  // ---------------------------------------------------------------------------

  /// EMQX Cloud Serverless broker hostname.
  /// Source: EMQX Cloud console > Cluster Overview > Connection address.
  static const String emqxHost = String.fromEnvironment('EMQX_HOST');

  /// EMQX broker TLS port. Typically 8883 for MQTT-over-TLS on EMQX Cloud
  /// Serverless. Plaintext port 1883 must not be used; all broker traffic
  /// crosses the public internet.
  static const int emqxPort =
      int.fromEnvironment('EMQX_PORT', defaultValue: 8883);

  /// EMQX subscriber credential — username component. This is the subscribe-
  /// only app credential from the ACL configuration (Backend Section 2.7),
  /// distinct from the device credential used by the ESP32 firmware.
  static const String emqxUsername = String.fromEnvironment('EMQX_USERNAME');

  /// EMQX subscriber credential — password component.
  static const String emqxPassword = String.fromEnvironment('EMQX_PASSWORD');

  // ---------------------------------------------------------------------------
  // Derived constants
  // ---------------------------------------------------------------------------

  /// Supabase Edge Function base URL, derived from [supabaseUrl]. Edge
  /// Function invocations append `/{functionName}` to this path.
  static String get edgeFunctionBaseUrl =>
      '$supabaseUrl/functions/v1';

  /// Heartbeat watchdog duration. If no heartbeat message is received within
  /// this window, [MqttClientService] sets `isUnresponsive = true` on the
  /// live status stream (Backend Architecture Section 2.5).
  static const Duration heartbeatTimeout = Duration(seconds: 90);

  /// MQTT reconnection initial backoff delay. Doubles on each failed attempt
  /// up to [mqttMaxReconnectDelay] (Flutter Architecture Section 5.1).
  static const Duration mqttInitialReconnectDelay = Duration(seconds: 2);

  /// MQTT reconnection backoff ceiling.
  static const Duration mqttMaxReconnectDelay = Duration(seconds: 60);

  // ---------------------------------------------------------------------------
  // Validation
  // ---------------------------------------------------------------------------

  /// Returns true if all required environment values were injected at build
  /// time. Call this during the splash sequence to surface a configuration
  /// error early rather than propagating null strings into service clients.
  static bool get isConfigured =>
      supabaseUrl.isNotEmpty &&
      supabasePublishableKey.isNotEmpty &&
      emqxHost.isNotEmpty &&
      emqxUsername.isNotEmpty &&
      emqxPassword.isNotEmpty;
}
